### ISSUE TITLE
TestObejscieCommand

### ISSUE THREAD

**Issue by PoLsKiPaLaCz** [yooniks/CasualProxy#3]
co ty robisz typie... nawet tam ani 1 pakietu z bp nie ma ps po co wysylasz handshake gdy sie on sam wysyla...

**Comment by kvbus** [comment]
Najmądrzejszy się odezwał 🙈

**Comment by wwdh00** [comment]
XDXD

**Comment by SKsteiner** [comment]
Gdyby było ObejscieCommand mógłbyś się przyczepić, lecz jak jest Test przez ObejscieCommand no to do czego tu się przypierdalać.

**Comment by yooniks** [comment]
Jeszcze 2 miesiące temu kupywałeś ode mnie pliki, typu drop, po czym to sam sprzedawałeś jako autorskie i sie pod to podpisywałeś. @PoLsKiPaLaCz , były to tylko testy, jest to napisane w minute, może dwie, nie wiem do czego sie przyczepiasz skoro nie znasz podstaw, chciałem osiągnąć coś typu 'wysyłam handshake do mc4u, i mam dostac pakiety od bpacka, które wysyła podczas łączenia i je skopiować' - ale nie jest to skończone, a nawet edytowane, nawet nie sprawdzalem czy działa, bo nie mam czasu.
A po dalszą dyskusje zapraszam na discord, chętnie cię ośmieszę jeśli chodzi o jave lub samego bukkita.

**Comment by yooniks** [comment]
A, no i jeszcze wspomnę o tym ,że jak ci wysłałem screenshota na skype, jak robie CasualProxy, i zobaczyłeś 'Command, CommandExecutor itd.' to od razu zacząłeś mnie o nie prosić od 16, do jakos 21, kilka razy ci odmówilem, potem przestałem ci odpisywać, kilka dni później napisałeś ,że dostałeś od kogoś innego :)
polaczek cebulaczek, dosc duzo sie juz osmieszyles
